const ACCESS_TOKEN = "GBEOIRUWEOIFHBDSKJFBDSFJHOIUSH";
const TOKEN_TIME_LIFE = '1h';
const EMAIL_PASSWORD = "pkxwadroafbpjgwo"
const EMAIL_USERNAME = "pviethoang123@gmail.com"

module.exports = {
    ACCESS_TOKEN: ACCESS_TOKEN,
    TOKEN_TIME_LIFE: TOKEN_TIME_LIFE,
    EMAIL_PASSWORD: EMAIL_PASSWORD,
    EMAIL_USERNAME: EMAIL_USERNAME
}